# Generated by Django 4.2.5 on 2023-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='meta_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='meta_tilte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='tage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
